// =========================================================================
// Woodland Library Hedgehog Cameo -- two-piece, Bambu A1 Mini
// Outer piece: blue PETG (frame + leaf border, recessed pocket)
// Inner piece: white PETG (bas-relief scene, press-fits into pocket)
//
// Artwork source: artwork.scad, generated by make_art.py from the same
// 55x55mm coordinate canvas the pieces below are built on, so every layer
// stacks in register automatically. Uses native polygon() data rather than
// SVG import -- OpenSCAD 2021.01's SVG importer fragments thin/spiky shapes.
// =========================================================================

include <artwork.scad>

// ---------- PARAMETERS --------------------------------------------------
D            = 55;      // overall blue disc diameter (mm) -- "a couple inches"
scene_r      = 24;      // radius of the scene / white insert (must match make_art.py SCENE_R)
canvas       = 55;      // artwork canvas size (must match make_art.py D)

insert_thk   = 2.2;     // white insert base-plate thickness
base_thk     = 4.0;     // blue base disc thickness
fit_clear    = 0.25;    // radial clearance between insert and pocket (press fit)
pocket_r     = scene_r + fit_clear;
pocket_depth = insert_thk;     // pocket depth == insert thickness -> insert sits flush,
                                // relief pokes up proud above the blue rim (classic cameo look)

// relief heights, measured above the flush insert top surface (mm)
h_shelf   = 0.6;
h_books   = 0.9;
h_leaves  = 1.0;
h_ground  = 0.7;
h_hh_sit  = 1.5;
h_hh_read = 1.6;
h_book    = 1.9;

leaf_border_h = 0.8;    // raised leaf motif height on the blue rim

add_hang_loop = true;
loop_extend   = 7;      // how far the loop sticks out past the disc edge
loop_od       = 9;
loop_id       = 3.6;    // fits a standard jump ring

$fn = 100;

// ---------- HELPERS -------------------------------------------------------
// artwork.scad layers live in canvas coordinates (0..55,0..55); every
// extrude below shifts by -canvas/2 first so the scene is centered on the
// OpenSCAD origin, matching the disc geometry.

// =========================================================================
// WHITE INSERT -- the bas-relief scene
// =========================================================================
module insert_piece() {
    union() {
        cylinder(h = insert_thk, r = scene_r);

        translate([-canvas/2, -canvas/2, insert_thk]) {
            linear_extrude(h_shelf)   layer_bg_shelf();
            linear_extrude(h_books)   layer_books();
            linear_extrude(h_leaves)  layer_leaves();
            linear_extrude(h_ground)  layer_ground();
            linear_extrude(h_hh_sit)  layer_hh_sit();
            linear_extrude(h_hh_read) layer_hh_read();
            linear_extrude(h_book)    layer_book();
        }
    }
}

// =========================================================================
// BLUE BASE -- frame, pocket, leaf border, optional hang loop
// =========================================================================
module base_piece() {
    difference() {
        union() {
            cylinder(h = base_thk, r = D/2);
            translate([-canvas/2, -canvas/2, base_thk])
                linear_extrude(leaf_border_h) layer_leaf_border();

            if (add_hang_loop) {
                translate([0, -(D/2 + loop_extend - loop_od/2), base_thk/2])
                    rotate([90, 0, 0])
                        difference() {
                            cylinder(h = base_thk*0.9, r = loop_od/2, center = true);
                            cylinder(h = base_thk*1.2, r = loop_id/2, center = true);
                        }
            }
        }
        // pocket for the insert
        translate([0, 0, base_thk - pocket_depth])
            cylinder(h = pocket_depth + 1, r = pocket_r);
    }
}

// =========================================================================
// RENDER SELECTOR
//   "insert"   -> white piece only, ready to print (relief face up)
//   "base"     -> blue piece only, ready to print (pocket face up)
//   "preview"  -> both pieces assembled, for visual review only (do not print)
// =========================================================================
part = "preview";

if (part == "insert") {
    insert_piece();
} else if (part == "base") {
    base_piece();
} else if (part == "preview") {
    color("SteelBlue") base_piece();
    color("White") translate([0, 0, base_thk - pocket_depth]) insert_piece();
}
