using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using NativeWebSocket;

namespace Meridian.AR
{
    /// <summary>
    /// Connects to the Inferno backend (e.g., via WebSocket or HTTP SSE)
    /// to receive the continuous stream of JSON UI schemas generated by Gemini.
    /// </summary>
    public class TelemetryRelay : MonoBehaviour
    {
        public string relayUrl = "ws://localhost:8080";
        public DynamicUIManager uiManager;
        
        private WebSocket websocket;

        async void Start()
        {
            Debug.Log($"[TelemetryRelay] Connecting to Relay API at {relayUrl}");
            websocket = new WebSocket(relayUrl);

            websocket.OnOpen += () =>
            {
                Debug.Log("[TelemetryRelay] Connection open!");
            };

            websocket.OnError += (e) =>
            {
                Debug.LogError("[TelemetryRelay] Error! " + e);
            };

            websocket.OnClose += (e) =>
            {
                Debug.Log("[TelemetryRelay] Connection closed!");
            };

            websocket.OnMessage += (bytes) =>
            {
                var message = System.Text.Encoding.UTF8.GetString(bytes);
                // Debug.Log($"[TelemetryRelay] Received {bytes.Length} bytes.");
                
                if (uiManager != null)
                {
                    // The UI Toolkit changes must be scheduled on the main thread
                    // Since NativeWebSocket's DispatchMessageQueue is called in Update(), 
                    // it is safe to interact with Unity objects here.
                    uiManager.OnSchemaReceived(message);
                }
            };

            await websocket.Connect();
        }

        void Update()
        {
            #if !UNITY_WEBGL || UNITY_EDITOR
            if (websocket != null)
            {
                // This dispatches the events (OnMessage, OnOpen, etc) on the main thread
                websocket.DispatchMessageQueue();
            }
            #endif
        }

        private async void OnApplicationQuit()
        {
            if (websocket != null)
            {
                await websocket.Close();
            }
        }
    }
}
